name: frontendBuild
on:
  push:
    branches:
      - master

jobs:
  TSLint_job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
        working-directory: ./frontend
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
          working-directory: ./frontend
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  
      - name: Test
        run: npm build
        working-directory: ./frontend  

