name: frontendRun
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
        
      - name: Lint
        run: npm run lint
        working-directory: ./frontend  
      - name: Build
        run: npm run build -- --prod
        working-directory: ./frontend  
      - name: Test
        run: npm test -- --configuration=ci
        working-directory: ./frontend  
      - name: E2E
        run: npm run e2e -- --configuration=ci
        working-directory: ./frontend  
