name: Test Master Branch

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  TSLint_job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
        working-directory: ./frontend
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
   
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        working-directory : ./backend
  test:
    name: Clean And Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean test
        working-directory : ./backend
      - name: Maven Verify
        run: mvn -B package
        working-directory : ./backend
